apiVersion: v1
kind: Service
metadata:
  name: gocache-client
  labels:
    app: gocache-client
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: client
  selector:
    app: gocache-client